services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: 'development:test'
        EXECJS_RUNTIME: Disabled
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    image: dariobastosdev/chatwoot:latest
    env_file: .env ## Change this file for customized env variables

  rails:
    <<: *base
    image: dariobastosdev/chatwoot:latest
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    networks:
      - chatwoot
    entrypoint: docker/entrypoints/rails.sh
    command: bundle exec rails s -p 3000 -b 0.0.0.0

  sidekiq:
    <<: *base
    image: dariobastosdev/chatwoot:latest
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    networks:
      - chatwoot
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    ports:
      - "5432:5432"
    networks:
      - chatwoot
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine
    restart: always
    networks:
      - chatwoot
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"

networks:
  chatwoot:
    driver: bridge

volumes:
  postgres:
  redis:
  bundle:
  packs:
  node_modules_rails:
