json.id stage.id
json.pipeline_id stage.pipeline_id
json.name stage.name
json.position stage.position
json.win_probability stage.win_probability
json.rotting_days stage.rotting_days
json.color stage.color
json.stage_type stage.stage_type
json.created_at stage.created_at
json.updated_at stage.updated_at
